/* Generated By:JavaCC: Do not edit this line. simplejavaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface simplejavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int DO = 12;
  /** RegularExpression Id. */
  int FOR = 13;
  /** RegularExpression Id. */
  int CLASS = 14;
  /** RegularExpression Id. */
  int RETURN = 15;
  /** RegularExpression Id. */
  int NEW = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;
  /** RegularExpression Id. */
  int PLUS = 21;
  /** RegularExpression Id. */
  int MINUS = 22;
  /** RegularExpression Id. */
  int MULTIPLY = 23;
  /** RegularExpression Id. */
  int DIVIDE = 24;
  /** RegularExpression Id. */
  int GETS = 25;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 26;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 27;
  /** RegularExpression Id. */
  int LEFT_BRACE = 28;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 29;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 30;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 31;
  /** RegularExpression Id. */
  int PERIOD = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int SEMICOLON = 34;
  /** RegularExpression Id. */
  int EQUALS = 35;
  /** RegularExpression Id. */
  int DOES_NOT_EQUAL = 36;
  /** RegularExpression Id. */
  int LESS_THAN = 37;
  /** RegularExpression Id. */
  int GREATER_THAN = 38;
  /** RegularExpression Id. */
  int LESS_THAN_OR_EQUAL_TO = 39;
  /** RegularExpression Id. */
  int GREATER_THAN_OR_EQUAL_TO = 40;
  /** RegularExpression Id. */
  int AND = 41;
  /** RegularExpression Id. */
  int OR = 42;
  /** RegularExpression Id. */
  int BANG = 43;
  /** RegularExpression Id. */
  int INCREMENT = 44;
  /** RegularExpression Id. */
  int DECREMENT = 45;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "<token of kind 4>",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"class\"",
    "\"return\"",
    "\"new\"",
    "\"true\"",
    "\"false\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\";\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"++\"",
    "\"--\"",
  };

}
